#!/usr/bin/env python3
"""
Generate README.md from resources.json.

resources.json is the source of truth. Run this script after editing
resources.json, or let the pre-commit hook do it automatically.

To install the hook:
    git config core.hooksPath .githooks
"""

import json
import re
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parent.parent

HEADER = """\
> **NOTE: Do not edit this file directly.** It is generated from [`resources.json`](resources.json).
> Make your changes in `resources.json`, then run `python3 scripts/generate_readme.py`.

# Awesome Biblical Data

A curated catalog of high-quality datasets and tools for biblical and linguistic
scholarship. Focused on what is freely available and how to get it onto your
machine or into your database.

**Suggest a resource:** [Open an issue](https://github.com/nida-institute/awesome-biblical-data/issues/new)

The machine-readable version of this catalog is [`resources.json`](resources.json).

---

"""

FOOTER = """\

---

## Contributing

To suggest a dataset, [open an issue](https://github.com/nida-institute/awesome-biblical-data/issues/new) with:
- Name and brief description
- License
- Where to get it (GitHub URL, download URL, or acquisition process)
- Format(s) available
- Why it meets a bar of scholarly quality

This catalog focuses on resources that are: (a) freely available or clearly
acquirable, (b) of genuine scholarly quality, and (c) useful for computational
work. Survey data, informal concordances, and ecclesial-only resources are
generally out of scope.

---

## License

This catalog is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).
Each dataset listed has its own license — see the License column for details.

[![CC BY-SA 4.0](https://licensebuttons.net/l/by-sa/4.0/88x31.png)](https://creativecommons.org/licenses/by-sa/4.0/)

_Maintained by the [NIDA Institute](https://github.com/nida-institute).
Machine-readable version: [`resources.json`](resources.json)._
"""


def make_anchor(text: str) -> str:
    """Replicate GitHub's heading-to-anchor algorithm."""
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s-]", "", text)
    text = re.sub(r"\s+", "-", text.strip())
    return text


def render_get_it(resource: dict) -> str:
    """Render the 'Get It' table cell from resource fields.

    Add a 'get_it' key to a resource in resources.json to override this
    with hand-crafted markdown (e.g. for multi-link or complex acquire steps).
    """
    if resource.get("get_it"):
        return resource["get_it"]

    parts = []
    github = resource.get("github")
    url = resource.get("url")
    acquire = resource.get("acquire", [])

    if github:
        owner_repo = github.replace("https://github.com/", "")
        parts.append(f"[{owner_repo}]({github})")
    elif url:
        domain = urlparse(url).netloc or url
        parts.append(f"[{domain}]({url})")

    for cmd in acquire:
        # Skip the bare git clone when the repo link already covers it
        if github and cmd.strip() == f"git clone {github}":
            continue
        parts.append(f"`{cmd}`")

    return " · ".join(parts)


def build_toc(categories: list) -> str:
    lines = [
        "## Contents",
        "",
        "- [Awesome Biblical Data](#awesome-biblical-data)",
        "  - [Contents](#contents)",
    ]
    for i, cat in enumerate(categories, 1):
        heading = f"{i}. {cat}"
        anchor = make_anchor(heading)
        display = heading.replace("&", "\\&")
        lines.append(f"  - [{display}](#{anchor})")
    lines.append("  - [Contributing](#contributing)")
    lines.append("  - [License](#license)")
    return "\n".join(lines)


def build_sections(resources: list, categories: list) -> str:
    by_cat = {}
    for r in resources:
        by_cat.setdefault(r["category"], []).append(r)

    sections = []
    for i, cat in enumerate(categories, 1):
        lines = [
            f"## {i}. {cat}",
            "",
            "| Name | Description | License | Format | Get It |",
            "|---|---|---|---|---|",
        ]
        for r in by_cat.get(cat, []):
            name = f"**{r['name']}**"
            desc = r.get("description", "").replace("|", "\\|")
            lic = r.get("license", "").replace("|", "\\|")
            fmt = ", ".join(r.get("formats", []))
            get_it = render_get_it(r)
            lines.append(f"| {name} | {desc} | {lic} | {fmt} | {get_it} |")
        sections.append("\n".join(lines))

    return "\n\n---\n\n".join(sections)


def generate() -> None:
    resources = json.loads((ROOT / "resources.json").read_text(encoding="utf-8"))

    # Unique categories in first-appearance order
    seen = set()
    categories = []
    for r in resources:
        cat = r["category"]
        if cat not in seen:
            seen.add(cat)
            categories.append(cat)

    toc = build_toc(categories)
    sections = build_sections(resources, categories)

    readme = HEADER + toc + "\n\n---\n\n" + sections + FOOTER
    (ROOT / "README.md").write_text(readme, encoding="utf-8")
    print(f"README.md regenerated from resources.json ({len(resources)} entries, {len(categories)} sections).")


if __name__ == "__main__":
    generate()
